# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


# Use modular headers globally
use_frameworks! :linkage => :static

target 'demoproject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  target 'demoprojectTests' do
    inherit! :complete
    # Pods for testing
  end


    # Include modular headers for Firebase dependencies
    pod 'FirebaseAuth', :modular_headers => true
    pod 'FirebaseCore', :modular_headers => true
    pod 'FirebaseFirestore', :modular_headers => true
    pod 'FirebaseStorage', :modular_headers => true # Add any additional Firebase pods as needed
  

    # Fix gRPC module map issues
    pod 'gRPC-C++', '~> 1.65.0'
    pod 'gRPC-Core', '~> 1.65.0'
    pod 'GoogleUtilities'


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
